### ISSUE TITLE
Only search for project in specified path

### ISSUE THREAD

**Issue by rchl** [deanishe/alfred-sublime-text#10]
I can set custom path (`[[path]]`) where to look for projects but it seems that it just adds to existing paths rather than replacing them. I would like to have it look only in the path I've specified. Is that possible? Maybe some new option in config to enable that behavior?

**Comment by deanishe** [comment]
> but it seems that it just adds to existing paths

Kinda.

Looks like I completely forgot how the workflow works myself when writing the README. Notably, this bit is complete bollocks:

> Note: You must edit the configuration and add some directories to search before using the workflow, or it won't do anything.

The workflow uses *three* scanners, one based on `mdfind`, one based on `locate` and one based on `find` to "fill in the gaps".

The first two always scan the entire system. Only the `find`-based scanner uses the `[[path]]` settings.

So if you only want to search the paths you've explicitly specified, you need to deactivate the system-wide scanners by setting `INTERVAL_LOCATE` and `INTERVAL_MDFIND` to `0` in the workflow's configuration sheet.

I'll go fix the README.

**Comment by rchl** [comment]
Very nice :)

It could be nicer if it all could be configured from one place (configuration file), but I won't complain as I got what I've asked for. :)

**Comment by deanishe** [comment]
> It could be nicer if it all could be configured from one place (configuration file)

Yes. I should have done this when I rewrote the workflow in Go.

I'll change it if the workflow needs another update.
