### ISSUE TITLE
Feature - Expand workflow to include....

### ISSUE THREAD

**Issue by TheSecEng** [deanishe/alfred-sublime-text#27]
Thoughts on expanding this workflows capabilities to include Searching package control and opening the ST Packages folder? If you think it would be useful to combine the two, I will work on your code base and make a PR when ready.

I've got a separate one I made before finding this one that does both of these.

PackageControl searching supports opening up a browser page on the **Homepage** or **Package Control** Page

<img width="567" alt="image" src="https://user-images.githubusercontent.com/32599364/72232652-7a33cf80-3590-11ea-8277-e868755dea14.png">

<img width="568" alt="image" src="https://user-images.githubusercontent.com/32599364/72232685-b0714f00-3590-11ea-9080-09e2aa9d0120.png">

**Comment by deanishe** [comment]
> Thoughts on expanding this workflows capabilities to include Searching package control and opening the ST Packages folder?

I'm not sure that's a good fit: I don't really advertise the fact, but the workflow also supports VS Code projects, so it's more of a "find your editor projects" workflow than a "Sublime Text stuff" one.

I would very much like to have your workflow, though.

Do you think they'd work better as a single workflow than as two separate ones?

**Comment by TheSecEng** [comment]
> > Thoughts on expanding this workflows capabilities to include Searching package control and opening the ST Packages folder?
> 
> I'm not sure that's a good fit: I don't really advertise the fact, but the workflow also supports VS Code projects, so it's more of a "find your editor projects" workflow than a "Sublime Text stuff" one.
> 
> I would very much like to have your workflow, though.
> 
> Do you think they'd work better as a single workflow than as two separate ones?

Ahh, I see, It would be odd to have a lot of custom ST support then VS project searching as well. It would feel more of a bolt on rather than part of the workflow. Separate workflows is fine in my eyes.

I'll finish updating the workflow tonight and then push changes to GH. Perhaps they can both reference each other complimentary. 

Do you mind if I use your ST icon from the workflow? For consistency.

**Comment by deanishe** [comment]
> Ahh, I see, It would be odd to have a lot of custom ST support then VS project searching as well.

That's my excuse. I've deleted VS Code because I got fed up with its bloat, and I'd sooner not add such a big new Sublime feature and then be asked to add a corresponding one for VS Code.

I also can't think of any additional features that combining the two would provide over two separate workflows.

> Do you mind if I use your ST icon from the workflow?

I thought I'd used Sublime's own icon… Sure, you can use it for me, but it's not really mine to give you. I've no idea where I got it from now. Perhaps I edited Sublime's icon. Can't remember.

**Comment by TheSecEng** [comment]
> I thought I'd used Sublime's own icon… Sure, you can use it for me, but it's not really mine to give you. I've no idea where I got it from now. Perhaps I edited Sublime's icon. Can't remember.

I think you did, but without the background.


See [Alfred-PackageControl](https://github.com/TheSecEng/Alfred-PackageControl)
