### ISSUE TITLE
Question about behavior

### ISSUE THREAD

**Issue by kfinlay** [deanishe/alfred-sublime-text#3]
When ST3 is closed and I use alfred-sublime-text, ST3 will open a new window and show the project file for the project I requested (or show the project file in the window of another project). When ST3 is open, ST3 will open the project window I wanted, which is the behavior I want. I suspect this is a function of some ST setting I've bungled. Any idea how to stop the first case? Thank you. Great workflow that I use all the time.

**Comment by deanishe** [comment]
It's just ST3 being weird, I'm afraid. The solution is to open .sublime-project files with ST3's `subl` command-line tool instead, which does the right thing and restores your project and workspace.

I used Automator to create an application that opens filepaths passed to it with `subl` and associated that app with .sublime-project files.

**Comment by kfinlay** [comment]
Thanks. That's helpful--I'll use the same workaround.

**Comment by mbigras** [comment]
This might be a similar problem. I'm getting multiple entries when I use the `.st` command, some of them open the config file that kfinly talked about, and some open up my actual sublime project. I've tried opening each project up from the terminal with `subl` but both the entries for both my projects (a total of four entries) still persist. Attached is a screen shot of what I'm talking about and my config file. What's going on here? Also seconding kfinlay, thanks for this workflow! 
![](http://cl.ly/3U2Y2P403F0D/Screen%20Shot%202016-05-08%20at%204.18.29%20PM.png)
![](http://cl.ly/1y2Y341e3T3K/Screen%20Shot%202016-05-08%20at%204.26.38%20PM.png)

```
{
  "excludes": [
    "/Applications/*.app/*"
  ], 
  "locatedb_cached": 0, 
  "search_directories": [
    "~/.config", 
    "~/.dotfiles",
    "/Users/max/sublime-projects"
  ]
}
```

**Comment by deanishe** [comment]
Not sure what's going on there. Could you [update to the latest version](https://github.com/deanishe/alfred-sublime-text/releases/latest) and see if the issue persists?

**Comment by mbigras** [comment]
right on! thanks dean it's all good now 😃 👍
