### ISSUE TITLE
Add ability to search within sublime projects

### ISSUE THREAD

**Issue by mbigras** [deanishe/alfred-sublime-text#4]
Hey dean,
I was thinking wouldn't it be cool if alfred-sublime-text had similar file creation options and file opening options as the [Sublime-AdvancedNewFile](https://github.com/skuroda/Sublime-AdvancedNewFile#advanced-path-usage) plugin. Meaning that we could do any number of things from the Alfred launch bar:
1. launch sublime project like normal by hitting enter
2. tab complete deeper into the project tree and hit enter to open a directory with all files opened just with that directory tree opened in the side bar
3. keep tab completing to a specific file and hit enter to open that specific file and directory tree (see attached image)
4. optionally enter text along the way to create a file within the directory tree (this is where it would be like Sublime-AdvancedNewFile)
5. also in a config file add aliases for different paths (also like Sublime-AdvancedNewFile)

Please see the attached image for a kind of example. What do you think?
![feature-request-sublime-alfred-workflow](https://cloud.githubusercontent.com/assets/5590632/15148826/eb891132-167b-11e6-872f-aac71f40b261.png)

**Comment by deanishe** [comment]
As noted on the Alfred forums, this kind of thing can't be done from *outside* Sublime Text, e.g. from Alfred.

You need a plugin running *inside* Sublime Text to expose such functionality, in which case you might as well just use Sublime's own interface.

**Comment by mbigras** [comment]
Hey @deanishe, what do you think about passing `subl` the `--command` flag? Check [this](https://forum.sublimetext.com/t/is-there-any-applescript-or-literally-any-language-support-for-accessing-the-python-console-from-outside-sublime/19930/3) out, do you think it's a dead end?

**Comment by deanishe** [comment]
What exactly is it you want the workflow to do?

**Comment by mbigras** [comment]
Broadly speaking I'd like the workflow to: create/open files+directories inside a sublime project from Alfred using a syntax similar to [Sublime-AdvancedNewFile](https://github.com/skuroda/Sublime-AdvancedNewFile#advanced-path-usage) except with the power of Alfred's search and drop down menus. To get more specific I can think of three use cases:

#### 1. Create a file inside an existing directory inside a sublime project
![feature-request](https://cloud.githubusercontent.com/assets/5590632/15465552/ea7f32ea-2089-11e6-8b4a-27179219bfd8.png)

#### 2. Create a file inside a directory that doesn't exist yet inside a sublime project
to be continued...but the spoiler alert is the workflow would create the needed directories to put the file into (just like advancednewfile)

#### 3. Open an existing file
mentioned in the first one but I'll get to this one tomorrow also

What do you think?

**Comment by deanishe** [comment]
I guess I'm not really seeing why you would want to do this in Alfred. Isn't this just duplicating Sublime's features in Alfred?

What would it do that you can't do already with Advanced New File?

**Comment by mbigras** [comment]
Ya it definitely makes sense to me why you think this isn't an important feature to add, because when you're creating/opening files while in sublime you're already in sublime, it's not so important to be able to get into your project from outside of sublime.

The reason why I'm so interested in adding this functionality is because I've been combining a bunch of different tools: git, github, sublime, lots of plugins, markdown, and alfred to basically create a note taking client. It's cool because sublime/git's ability to search/organize notes is far superior to any other apps that I've used (like evernote for example) and github provides the ability to interface with your notes in the cloud, both sublime and github can render my markdown. So far I'm really pleased with the whole thing, but one bottle neck is I'd like to be able to quickly make notes from the Alfred launch bar similar to the Notes workflow, instead of having to manually go into sublime every time I want to make a note.

Especially after reading your response I would understand if you don't want to add it to your existing workflow. But the way I laid out the use case above (and I could make more if you're interested) I don't think it actually affects the existing functionality all that much, yes you have to press enter twice, but it could be a config option you could toggle on/off (and perhaps off by default) if you wanted to be able to open/create specific files/directories.

Also it could be a stand alone workflow. I don't have any experience creating useful plugins/workflows yet, but I'm planning on working through your tutorials to learn more. I have some ideas about how I could do it using this new `--command` parameter that I didn't know about. I'm also curious, did you know about that parameter? Because to me it seems like it could be the pinhole that lets us into sublime from the outside, which (as you said at the beginning of this issue, was thought not possible)

Anyways, I'm looking forward to hearing from you

**Comment by deanishe** [comment]
It's not that I doubt the value or utility of the feature, it's the effort-to-payoff ratio that I'm not convinced by.

If what you want to do is add notes, why not build a workflow for notes?

The fundamental problem with all of this is that Sublime Text isn't externally scriptable. It won't tell you what projects and files it has open in which windows, and any `subl --command` you run will be executed in whichever Sublime window is frontmost (or a newly-created one).

If the workflow isn't able to talk to the Sublime window a specific project is already open in, it can't do what you're suggesting (at least, not properly).

Without that, you might as well just add a "Create New Note Here" File Action for folders.
