### ISSUE TITLE
Expose chosen  result to other workflows

### ISSUE THREAD

**Issue by redgluten** [deanishe/alfred-sublime-text#44]
I’ve been trying to figure out a way to call this workflow from my own to do additional actions on the selected project path (e.g: opening a terminal window and cd-ing to the project path, opening the git repo…). Unfortunately even tho I can use a `Call External Trigger` to do that it will just pass my own inputs to this workflow but without any feedbacks. So this issue is either a call for help or a Feature Request: is it possible to expose the result of the filtering script to other Alfred workflows?

**Comment by deanishe** [comment]
> is it possible to expose the result of the filtering script to other Alfred workflows?

As the results are files, you could use a [File Action](https://www.alfredapp.com/help/features/actions/) to pass the project file (but not the project directory) to your own workflow.

But it sounds like [my Git Repos workflow](https://github.com/deanishe/alfred-repos) might be more useful to you.

**Comment by redgluten** [comment]
Oh super interesting, I’ll explore these options, thanks!
