### ISSUE TITLE
"Reveal file in Finder" -> go to project and not to .sublime-project

### ISSUE THREAD

**Issue by elalemanyo** [deanishe/alfred-sublime-text#5]
Hi,
I have all my .sublime-project files on one location, and this is not the root from each project. Will be possible to have an action to go to the root from project on finder?

Thanks!

**Comment by deanishe** [comment]
Added in [v3.0.1](https://github.com/deanishe/alfred-sublime-text/releases/tag/v3.0.1).

**Comment by elalemanyo** [comment]
Thanks! Works great!

**Comment by deanishe** [comment]
And it only took 3 years! 🤭
