### ISSUE TITLE
Support to copy the path of project by Command-C

### ISSUE THREAD

**Issue by edentsai** [deanishe/alfred-sublime-text#51]
Currently, I can hold <kbd>Command</kbd> to select a project to open it in Finder, it's very convenient.

sometimes I want to quickly copy the folder path into the clipboard,
but when I select a project and press <kbd>Command-C</kbd>, it will copy the arguments like this:

```txt
(
    "-project",
    "--",
    "/path/to/project/project.sublime-project"
)
```

Hopes it can support <kbd>Command+-C</kbd> to just copy the path of project
to clipboard:

```txt
/path/to/project/project.sublime-project
```

or copy the folder path of project will be better:

```txt
/path/to/project
```

thanks for this awesome workflow,
it helps me a lot.

**Comment by deanishe** [comment]
Thanks for the suggestion. Added in [v3.3.0-beta](https://github.com/deanishe/alfred-sublime-text/releases/tag/v3.3.0-beta).

**Comment by edentsai** [comment]
thank you 👍 👍 👍
