### ISSUE TITLE
99% CPU Usage of Python Script

### ISSUE THREAD

**Issue by spieglio** [deanishe/alfred-sublime-text#6]
I have no idea why this is happening. But it seems to come from this Alfred Workflow.

It would be massively useful to know how I can get rid of this problem. Because it is rather anoying to have the CPU at 99% and thus the fans running all the time :)

Thanks :)

<img width="876" alt="python__86888_" src="https://cloud.githubusercontent.com/assets/1096384/15658109/aa00cb72-26b8-11e6-97cb-52c139e5c546.png">

**Comment by deanishe** [comment]
Could you try resetting the workflow with `.st workflow:reset`?

**Comment by spieglio** [comment]
I'll try this the next time the problem arises.

**Comment by dpidan** [comment]
Same issue here using Alfred 3 and ST3. Tried `.st workflow:reset` but was not a recognized command.

**Comment by deanishe** [comment]
What does the log file say? It's likely the background update script that's causing the issue.

**Comment by ccna4life** [comment]
Any status on this fix? I am having the same issue

**Comment by deanishe** [comment]
I can't replicate the issue, so no.

If we could figure out a common feature of your workflow configurations, it might be possible.

**Comment by pzgz** [comment]
Having same issue, and traced to this issue tracker as well. No clue though, check that log file file operated by the `Python` thread, not much clues though. I have to force quit the `Python` thread in Activity Monitor and the CPU went down. This issue occured for me several times, no more clues for now.

**Comment by pzgz** [comment]
@deanishe FYI, I didn't spent lots of time for debugging the issue root cause,  but I simply updated the `workflow` module to your latest version from https://github.com/deanishe/alfred-workflow/tree/master/workflow , and looks like the issue was fixed.

**Comment by SalvatoreT** [comment]
I hit the same issue on Alfred 3.4 Build 850

**Comment by deanishe** [comment]
It's an issue with Sierra.

Run [this workflow](https://github.com/deanishe/alfred-fixum) to fix any workflows you have that are affected by the bug.
