### ISSUE TITLE
Folder was moved and renamed, now not being picked up

### ISSUE THREAD

**Issue by rkpatel33** [deanishe/alfred-sublime-text#7]
I moved a folder to a new location and renamed it, but the `.st` command is not picking it up. The search result still point to the old location. The new location is here:

```/Users/rishi/Dropbox (Personal)/Mackup_MacbookPro2017/Sublime-projects/asset-allocation.sublime-project```

But the search result in Alfred still only show the old location, which does not even exist anymore:

![image](https://cloud.githubusercontent.com/assets/3799489/25913419/7e4a54f0-356f-11e7-9421-967eb0ee6042.png)

`mdfind` in terminal finds it fine:

```shell
rishi@Rishis-MacBook-Pro-2017:~|⇒  mdfind "asset-allocation"
...
/Users/rishi/Dropbox (Personal)/Mackup_MacbookPro2017/Sublime-projects/asset-allocation.sublime-workspace
/Users/rishi/Dropbox (Personal)/Mackup_MacbookPro2017/Sublime-projects/asset-allocation.sublime-project
...
```

Any suggestions? Not sure what could be wrong.

**Comment by deanishe** [comment]
What does the log file say? `.st workflow:openlog`

That isn't the command the workflow uses. Try `mdfind -name .sublime-project`

It's possible the workflow was picking up the file via `locate`, whose database isn't updated very often.

Also check your settings file. Run `.st workflow:opendata` and look at `settings.json`. It's possible you've excluded that path for some reason.

If you have a lot of projects in there, might be worth adding it to `search_directories` (they are explicitly searched using `find`).

**Comment by rkpatel33** [comment]
Thanks for the suggestions, but the issue seems to have been fixed on a
reboot.


_________________________
Rishi Patel | mail@rishinyc.com

**Comment by deanishe** [comment]
Glad it's working
