### ISSUE TITLE
Does not work if Sublime is not running

### ISSUE THREAD

**Issue by shreyasminocha** [deanishe/alfred-sublime-text#8]
The workflow opens the `.sublime-project` file itself if Sublime is not already running.

**Comment by deanishe** [comment]
*Sublime* opens the `.sublime-project` file. It's not the workflow's fault.

The workflow simply asks macOS to open the `.sublime-project` file in the default application for that filetype.

**Comment by shreyasminocha** [comment]
I'm probably wrong, but isn't the project supposed to be loaded as it would with `Project`→`Open Project...`?

**Comment by deanishe** [comment]
One would think so, yes. But that isn't what Sublime does.

I can't change the behaviour of Sublime Text. You need to ask its developer(s).

**Comment by schrodincat** [comment]
Hi, I know how to fix it, but it would require user to provide path to Sublime Text.app in workflow settings. Do you want me to do a PR with fix?

**Comment by deanishe** [comment]
Thanks, @schrodincat, but it's okay. I'm [rewriting the workflow](https://github.com/deanishe/alfred-sublime-text/tree/v3) in Go, and it now uses the `subl` command for proper behaviour.

FWIW, you can get the path to an application with AppleScript:

```applescript
tell application "Finder" to get (POSIX path of (path to application "Sublime Text"))
```

**Comment by schrodincat** [comment]
Ok, then.
`subl` is exactly what I was talking about. I didn’t know how to get the path to it, though, thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
