### ISSUE TITLE
Incompatible with macOS Sierra 10.12.4+

### ISSUE THREAD

**Issue by sundarv85** [deanishe/alfred-sublime-text#9]
Just installed the workflow in Mac. Got the below error

![image](https://user-images.githubusercontent.com/11090193/46193393-4fbbf580-c2fe-11e8-8191-d8c9d218bcad.png)

Running MacOS Sierra 10.13.6

**Comment by deanishe** [comment]
Install and run [the Fixum workflow](https://github.com/deanishe/alfred-fixum/), as described in the instructions behind "Click here to find out how to update".

**Comment by sundarv85** [comment]
That fixes the issue!
